name: ZPT CI

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  lint_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: HTML/CSS lint (basic)
        run: |
          npx -y htmlhint "**/*.html" || true
          npx -y stylelint "**/*.css" || true

  # Compute the URL we'll test: Deploy Preview on PRs, fallback to PREVIEW_URL secret on pushes.
    compute_preview_url:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.out.outputs.url }}
    steps:
      - name: Determine preview URL
        id: out
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "url=https://deploy-preview-${{ github.event.pull_request.number }}--keen-souffle-c7c059.netlify.app/" >> "$GITHUB_OUTPUT"
          else
            echo "url=${{ secrets.PREVIEW_URL }}" >> "$GITHUB_OUTPUT"
          fi

  lighthouse:
    runs-on: ubuntu-latest
    needs: [lint_build, compute_preview_url]
    steps:
      - uses: actions/checkout@v4

      - name: Show preview URL
        run: echo "Preview URL -> $URL"
        env:
          URL: ${{ needs.compute_preview_url.outputs.url }}

      - name: Fail early if URL is empty
        run: |
          if [ -z "${URL}" ]; then
            echo "::error::Preview URL is empty" && exit 1
          fi
        env:
          URL: ${{ needs.compute_preview_url.outputs.url }}

      - name: Install LHCI
        run: npm i -g @lhci/cli@0.13.x

      - name: Run Lighthouse via LHCI
        env:
          LHCI_COLLECT__URL: ${{ needs.compute_preview_url.outputs.url }}
          LHCI_UPLOAD__TARGET: temporary-public-storage
        run: lhci autorun

  accessibility:
    runs-on: ubuntu-latest
    needs: [lint_build, compute_preview_url]
    steps:
      - uses: actions/checkout@v4

      - name: Show preview URL
        run: echo "Preview URL -> $URL"
        env:
          URL: ${{ needs.compute_preview_url.outputs.url }}

      - name: Run Pa11y on Preview
        run: pa11y "$URL" --reporter cli || true
        env:
          URL: ${{ needs.compute_preview_url.outputs.url }}

      - name: Install Pa11y
        run: npm i -g pa11y
